import type { TaskContextLLMPort,TaskContextLlmRequest,TaskContextLlmResult } from "../../ports/task-context-llm.port";
import type { LlmRequest,LlmResult } from "../../ports/llm.port";
import { taskContextOutputJsonSchema } from "./task-context-output.schema";
export interface ResponsesClient { responses:{create(input:unknown):Promise<{id:string;status:string;output_text?:string;refusal?:string}>} }
export class NativeOpenAiResponsesClient implements ResponsesClient {responses={create:async(input:unknown)=>{const apiKey=process.env.OPENAI_API_KEY;if(!apiKey)throw new Error("NETWORK_OPENAI_NOT_CONFIGURED");const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{authorization:`Bearer ${apiKey}`,"content-type":"application/json"},body:JSON.stringify(input)});if(!response.ok)throw new Error(`NETWORK_OPENAI_${response.status}`);const body=await response.json() as {id:string;status:string;output_text?:string;refusal?:string};return body;}};}
export class OpenAiTaskContextAdapter implements TaskContextLLMPort {
  constructor(private readonly client:ResponsesClient,private readonly model=process.env.OPENAI_MODEL??"gpt-5.6-luna"){}
  execute(request:LlmRequest):Promise<LlmResult>{void request;return Promise.resolve({ok:false,code:"TERMINAL"});}
  async executeTaskContext(request:TaskContextLlmRequest):Promise<TaskContextLlmResult>{try{const response=await this.client.responses.create({model:this.model,reasoning:{effort:"low"},input:[{role:"user",content:[{type:"input_text",text:request.promptText??"Analyze the IELTS Task 1 image."},{type:"input_image",image_url:`data:${request.image.mediaType};base64,${Buffer.from(request.image.bytes).toString("base64")}`,detail:"original"}]}],text:{format:{type:"json_schema",name:"task_context",strict:true,schema:taskContextOutputJsonSchema}}});if(response.refusal)return{ok:false,code:"REFUSAL"};if(response.status!=="completed")return{ok:false,code:"INCOMPLETE"};if(!response.output_text)return{ok:false,code:"INVALID_JSON"};try{return{ok:true,value:JSON.parse(response.output_text),model:this.model,responseId:response.id};}catch{return{ok:false,code:"INVALID_JSON"};}}catch(error){return{ok:false,code:error instanceof Error&&/timeout/i.test(error.message)?"TIMEOUT":"NETWORK"};}}
}
