export const aiSettingsErrorCodes = [
  "AI_SETTINGS_INVALID",
  "AI_SECRET_NOT_CONFIGURED",
  "AI_PAID_PROBE_CONSENT_REQUIRED",
  "AI_VERIFICATION_STALE",
  "AI_ROLE_NOT_CONFIGURED",
  "AI_IDEMPOTENCY_CONFLICT",
  "AI_PROBE_IN_PROGRESS",
  "AI_PROVIDER_AUTH_FAILED",
  "AI_PROVIDER_PERMISSION_DENIED",
  "AI_MODEL_NOT_FOUND",
  "AI_MODEL_INCOMPATIBLE",
  "AI_PROVIDER_RATE_OR_QUOTA_LIMITED",
  "AI_SECRET_STORE_UNAVAILABLE",
  "AI_PROVIDER_UNREACHABLE",
  "AI_PROVIDER_UNAVAILABLE",
  "AI_PROVIDER_TIMEOUT",
  "AI_PROVIDER_RESPONSE_INVALID",
] as const;

export type AiSettingsErrorCode = (typeof aiSettingsErrorCodes)[number];
