import { z } from "zod";

export const eventTypeSchema = z.enum([
  "essay.session_created",
  "essay.revision_saved",
  "sentence.completion_candidate",
  "sentence.check_requested",
  "sentence.check_cancelled",
  "sentence.result_stale",
  "paragraph.completion_candidate",
  "paragraph.check_requested",
  "paragraph.check_cancelled",
  "paragraph.check_skipped",
  "paragraph.result_stale",
  "feedback.candidate_created",
  "feedback.shown",
  "feedback.deferred",
  "feedback.ignored",
  "feedback.suppressed",
  "feedback.stale",
  "feedback.policy_state_changed",
  "task.context_ready",
  "task.context_degraded",
  "task.context_unavailable",
  "task.fact_uncertain",
  "submission.word_count_risk_required",
  "submission.cancelled",
  "essay.submitted",
  "assessment.started",
  "assessment.limited_by_task_context",
  "assessment.completed",
  "assessment.failed",
  "memory.evidence_added",
  "memory.state_changed",
  "memory.deleted",
  "essay.deletion_started",
  "essay.deleted",
  "memory.recompute_requested",
  "memory.recomputed",
]);

export type EventType = z.infer<typeof eventTypeSchema>;
