import { z } from "zod";

export const reasonCodeSchema = z.enum([
  "SESSION_STARTED",
  "AUTOSAVE_SUCCEEDED",
  "REVISION_CONFLICT",
  "SENTENCE_PUNCTUATION_STABLE",
  "SENTENCE_CURSOR_LEFT",
  "SENTENCE_NEXT_STARTED",
  "SENTENCE_TEXT_CHANGED",
  "SENTENCE_BOUNDARY_CHANGED",
  "PARAGRAPH_STABLE",
  "PARAGRAPH_CURSOR_LEFT",
  "PARAGRAPH_MANUAL_REQUEST",
  "PARAGRAPH_TEXT_CHANGED",
  "PARAGRAPH_BOUNDARY_CHANGED",
  "INCOMPLETE",
  "ESSAY_NOT_DRAFT",
  "DEPENDENCY_CHANGED",
  "DUPLICATE_REQUEST",
]);

export type ReasonCode = z.infer<typeof reasonCodeSchema>;
