import { sql } from "drizzle-orm";
import { integer, primaryKey, sqliteTable, text, unique, uniqueIndex } from "drizzle-orm/sqlite-core";

export const writingTasks = sqliteTable("writing_tasks", { id: text("id").primaryKey(), promptText: text("prompt_text").notNull(), txtFileName: text("txt_file_name"), imagePlaceholderKind: text("image_placeholder_kind").notNull(), imageBlobId: text("image_blob_id"), imageMediaType: text("image_media_type"), imageSha256: text("image_sha256"), intakeStatus: text("intake_status"), activeAttemptId: text("active_attempt_id"), currentTaskContextVersionId: text("current_task_context_version_id") });
export const essaySessions = sqliteTable("essay_sessions", { id: text("id").primaryKey(), userId: text("user_id").notNull(), taskId: text("task_id").notNull(), status: text("status").notNull(), currentRevisionId: text("current_revision_id").notNull(), startedAt: text("started_at").notNull(), submittedAt: text("submitted_at"), timerElapsedMs: integer("timer_elapsed_ms").notNull(), timerRunningSince: text("timer_running_since"), clientRequestId: text("client_request_id").notNull().unique() });
export const essayRevisions = sqliteTable("essay_revisions", { id: text("id").primaryKey(), sessionId: text("session_id").notNull(), revisionNo: integer("revision_no").notNull(), plainText: text("plain_text").notNull(), contentJson: text("content_json").notNull(), wordCount: integer("word_count").notNull(), textHash: text("text_hash").notNull(), createdAt: text("created_at").notNull() }, (table) => [unique("essay_revisions_session_revision_no_unique").on(table.sessionId, table.revisionNo)]);
export const draftMutations = sqliteTable("draft_mutations", { id: text("id").notNull(), sessionId: text("session_id").notNull(), status: text("status").notNull(), revisionId: text("revision_id"), currentRevisionId: text("current_revision_id") }, (table) => [primaryKey({ columns: [table.sessionId, table.id] })]);
export const domainEvents = sqliteTable("domain_events", { id: text("id").primaryKey(), aggregateType: text("aggregate_type").notNull(), aggregateId: text("aggregate_id").notNull(), eventType: text("event_type").notNull(), payloadJson: text("payload_json").notNull(), occurredAt: text("occurred_at").notNull(), correlationId: text("correlation_id").notNull() });
export const taskContextAttempts = sqliteTable("task_context_attempts", { id: text("id").primaryKey(), taskId: text("task_id").notNull(), inputHash: text("input_hash").notNull(), promptVersion: text("prompt_version").notNull(), schemaVersion: integer("schema_version").notNull(), idempotencyKey: text("idempotency_key").notNull(), state: text("state").notNull(), callCount: integer("call_count").notNull(), jobId: text("job_id"), failureCode: text("failure_code"), startedAt: text("started_at").notNull(), finishedAt: text("finished_at"), providerKind: text("provider_kind"), connectionId: text("connection_id"), configRevision: integer("config_revision"), normalizedEndpoint: text("normalized_endpoint"), secretRevision: integer("secret_revision"), secretRef: text("secret_ref"), requestedModelId: text("requested_model_id"), verificationId: text("verification_id"), verificationFingerprint: text("verification_fingerprint"), adapterContractVersion: text("adapter_contract_version"), invocationFingerprint: text("invocation_fingerprint") }, (table) => [unique("task_context_attempts_task_idempotency_unique").on(table.taskId, table.idempotencyKey)]);
export const taskContextVersions = sqliteTable("task_context_versions", { id: text("id").primaryKey(), taskId: text("task_id").notNull(), version: integer("version").notNull(), status: text("status").notNull(), contextJson: text("context_json"), limitationsJson: text("limitations_json").notNull(), sourceImageSha256: text("source_image_sha256").notNull(), promptVersion: text("prompt_version").notNull(), schemaVersion: integer("schema_version").notNull(), model: text("model").notNull(), createdAt: text("created_at").notNull(), sourceAttemptId: text("source_attempt_id"), providerKind: text("provider_kind"), connectionId: text("connection_id"), configRevision: integer("config_revision"), normalizedEndpoint: text("normalized_endpoint"), secretRevision: integer("secret_revision"), requestedModelId: text("requested_model_id"), verificationId: text("verification_id"), verificationFingerprint: text("verification_fingerprint"), adapterContractVersion: text("adapter_contract_version"), invocationFingerprint: text("invocation_fingerprint") }, (table) => [unique("task_context_versions_task_version_unique").on(table.taskId, table.version)]);

export const aiProviderConnections = sqliteTable("ai_provider_connections", {
  id: text("id").primaryKey(), providerKind: text("provider_kind").notNull().unique(), normalizedBaseUrl: text("normalized_base_url").notNull(), modelId: text("model_id"), secretRef: text("secret_ref").notNull(), secretRevision: integer("secret_revision").notNull(), configRevision: integer("config_revision").notNull(), connectionTestState: text("connection_test_state").notNull(), connectionTestedAt: text("connection_tested_at"), connectionTestFailureCode: text("connection_test_failure_code"), credentialCleanupState: text("credential_cleanup_state").notNull(), createdAt: text("created_at").notNull(), updatedAt: text("updated_at").notNull(),
});

export const aiProbeRequests = sqliteTable("ai_probe_requests", {
  id: text("id").primaryKey(), requestId: text("request_id").notNull().unique(), operation: text("operation").notNull(), operationFingerprint: text("operation_fingerprint").notNull(), providerKind: text("provider_kind").notNull(), connectionId: text("connection_id").notNull(), configRevision: integer("config_revision").notNull(), normalizedEndpoint: text("normalized_endpoint").notNull(), secretRevision: integer("secret_revision").notNull(), secretRef: text("secret_ref").notNull(), modelId: text("model_id").notNull(), role: text("role"), state: text("state").notNull(), leaseExpiresAt: text("lease_expires_at"), stableResultCode: text("stable_result_code"), createdAt: text("created_at").notNull(), finishedAt: text("finished_at"),
}, (table) => [uniqueIndex("ai_probe_requests_one_live_claim_unique").on(table.operationFingerprint).where(sql`${table.state} = 'CLAIMED'`)]);

export const aiModelVerifications = sqliteTable("ai_model_verifications", {
  id: text("id").primaryKey(), connectionId: text("connection_id").notNull(), modelId: text("model_id").notNull(), role: text("role").notNull(), state: text("state").notNull(), verificationFingerprint: text("verification_fingerprint").notNull(), endpointCheck: text("endpoint_check").notNull(), credentialCheck: text("credential_check").notNull(), modelAccessCheck: text("model_access_check").notNull(), textInputCheck: text("text_input_check").notNull(), imageInputCheck: text("image_input_check").notNull(), structuredOutputCheck: text("structured_output_check").notNull(), taskContextSchemaCheck: text("task_context_schema_check").notNull(), essayFeedbackSchemaCheck: text("essay_feedback_schema_check").notNull(), lastProbeRequestId: text("last_probe_request_id"), failureCode: text("failure_code"), verifiedAt: text("verified_at"), updatedAt: text("updated_at").notNull(),
}, (table) => [unique("ai_model_verifications_binding_unique").on(table.connectionId, table.modelId, table.role)]);

export const aiRoleSelections = sqliteTable("ai_role_selections", {
  role: text("role").primaryKey(), connectionId: text("connection_id").notNull(), modelId: text("model_id").notNull(), verificationId: text("verification_id").notNull(), lastSuccessfulSnapshotJson: text("last_successful_snapshot_json"), lastSuccessfulAt: text("last_successful_at"), updatedAt: text("updated_at").notNull(),
});
